added tabs component
peaksoft-school/peaksoft-lms-js9 pull request #13
Opened 2023-07-10 13:49 UTC by nurzhigitabdymanapov

2023-07-10 14:15 UTC, AvazMAX approved these changes

2023-07-10 14:16 UTC, NurPro approved these changes

2023-07-11 05:16 UTC, AziatAbd requested changes

2023-07-11 05:16 UTC, AziatAbd commented on src/components/UI/tabs/Tabs.jsx
> +export const MyTabs = ({ labelOne, labelTwo, ...rest }) => {
просто tabs и убрать rest

2023-07-11 05:16 UTC, AziatAbd commented on src/components/UI/tabs/Tabs.jsx
> +         <NavLink to="/students" className="activee">
сделайте так чтобы через пропсы можно было передать путь для ' to '

2023-07-11 07:00 UTC, merged