added meatball
peaksoft-school/peaksoft-lms-js9 pull request #15
Opened 2023-07-11 10:25 UTC by NurPro

2023-07-11 10:43 UTC, itsmon17 approved these changes

2023-07-11 10:46 UTC, nurzhigitabdymanapov approved these changes

2023-07-11 10:46 UTC, AvazMAX approved these changes

2023-07-11 10:49 UTC, Daniel-Narpaev approved these changes

2023-07-12 06:30 UTC, AziatAbd requested changes

2023-07-12 06:30 UTC, AziatAbd commented on src/components/meatBall/MeatBall.jsx
> +         <Button
iconButton должен быть

2023-07-12 06:30 UTC, AziatAbd commented on src/components/meatBall/MeatBall.jsx
> +            Options
иконка

2023-07-12 06:30 UTC, AziatAbd commented
по умолчанию бир массив кылып койсонуз

2023-07-13 11:33 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/bfb5d301-1a11-4048-b237-577b346d3af6)
мен озум кошкон данный чыкты, бирок статичный данный дагы туруп калды

2023-07-13 11:34 UTC, AziatAbd requested changes

2023-07-13 11:34 UTC, AziatAbd commented on src/components/meatBall/MeatBall.jsx
> +         </Button>
iconButton ичинде MeatBallIcon болуш

2023-07-14 11:25 UTC, AziatAbd requested changes

2023-07-14 11:25 UTC, AziatAbd commented on src/components/meatBall/MeatBall.jsx
> +export default function MeatBall({ menuItems: parentMenuItems = [], onClick }) {
бир массив с данными берип койсонуз пустой кылбай

2023-07-15 03:32 UTC, merged