save
peaksoft-school/peaksoft-lms-js9 pull request #20
Opened 2023-07-12 06:08 UTC by nurzhigitabdymanapov

2023-07-14 15:35 UTC, AvazMAX approved these changes

2023-07-15 13:24 UTC, AziatAbd requested changes

2023-07-15 13:24 UTC, AziatAbd commented on src/pages/CreatePassword.jsx
> +                     id="1"
откройте состояние для **ВСЕХ** инпутов и сделайте валидацию, можете использовать react-hook-form или formik для состоянии и yup для валидации

2023-07-15 13:24 UTC, AziatAbd commented on src/pages/CreatePassword.jsx
все файлы которые находятся в pages должны быть в папке containers > public

2023-07-19 03:51 UTC, merged