Feature/test result
peaksoft-school/peaksoft-lms-js9 pull request #32
Opened 2023-07-21 11:43 UTC by nurzhigitabdymanapov

2023-07-21 11:50 UTC, AvazMAX approved these changes

2023-07-21 13:32 UTC, AziatAbd requested changes

2023-07-21 13:32 UTC, AziatAbd commented on src/components/testResult/TestResult.jsx
> +                     <p>{el.point} баллов из 1</p>
N балл из 1? разве не из 10

2023-07-21 13:32 UTC, AziatAbd commented on src/index.css
> +   background-color: #e48989;
зачем это

2023-07-21 13:36 UTC, AziatAbd requested changes

2023-07-21 13:36 UTC, AziatAbd commented on src/utils/constants/testResult.js
чё за говнокод? это же моковые данные, зачем открывать в структуре файл для этого? поставь их в файле компоненты, потом при интеграции с бэком просто удалишь код

2023-07-22 06:09 UTC, nurzhigitabdymanapov commented on src/components/testResult/TestResult.jsx
> +                     <p>{el.point} баллов из 1</p>
0 балл из 1 деп туруптур фигмада

2023-07-22 06:51 UTC, merged