Feature/sign in api
peaksoft-school/peaksoft-lms-js9 pull request #36
Opened 2023-08-11 15:23 UTC by nurzhigitabdymanapov

2023-08-11 15:25 UTC, itsmon17 approved these changes

2023-08-12 05:43 UTC, AziatAbd requested changes

2023-08-12 05:43 UTC, AziatAbd commented on src/containers/ForgotModal.jsx
если я напишу не зарегистрированный email то должна появиться tostify, а то ничего нет и не понимаешь почему не приходит сообщение по почте

2023-08-12 05:43 UTC, AziatAbd commented on src/containers/CreatePassword.jsx
здесь тоже после успешного запроса или ошибки пусть выйдет toast

2023-08-12 05:43 UTC, AziatAbd commented on src/containers/SignInPage.jsx
> +            })
старайтесь unwrap вообще не использовать. Передайте через пропсы showSnackbar и используйте его там а не здесь

2023-08-12 05:43 UTC, AziatAbd commented on src/store/signIn/signInThunk.js
> +         console.log(response.data)
все console.log() удалите

2023-08-12 05:43 UTC, AziatAbd commented on src/store/signIn/signInSlice.js
> +            state.isAuthorization = true
разве в сбросе пароля мы авторизуемся?

2023-08-12 05:43 UTC, AziatAbd commented on src/store/signIn/signInSlice.js
> +            state.isAuthorization = true
тоже самое

2023-08-12 05:43 UTC, AziatAbd commented on .eslintrc.json
> +      "no-param-reassign": "off",
всё подряд не оффайте

2023-08-12 05:43 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/c7aecaec-cdb2-4c62-8ab8-c4a2acb320ce)
cursor: pointer для него

2023-08-14 11:29 UTC, AziatAbd approved these changes

2023-08-14 11:29 UTC, merged