Feature/create lesson
peaksoft-school/peaksoft-lms-js9 pull request #38
Opened 2023-08-21 05:31 UTC by NurPro

2023-08-21 05:39 UTC, nurzhigitabdymanapov approved these changes

2023-08-22 06:48 UTC, NurPro commented
конфликти чечип коём карап коё бергиле😁

2023-08-23 08:23 UTC, AziatAbd requested changes

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +            {lesson?.map((el) => (
lesson?.map() так больше не делайте, сделайте полную проверку на массив если нету данных пусть выйдет какой-нибудь текст, а не это

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +      console.log(e.target.value)
баардык консольдорду очурун

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +      dispatch(getLesson(courseId))
бир функциянын ичинде эки dispatch жазбагыла

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +      dispatch(getLesson(courseId))
thunk'тын ичинде get запрос чыкыргыла

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +      dispatch(getLesson(courseId))
тоже самое

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +   const onChangeHPostandler = (e) => {
что с названием?

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +   const postLessonS = () => {
что за S в конце

2023-08-23 08:23 UTC, AziatAbd commented on src/pages/instructor/MyCourses.jsx
> +      console.log(e.target.value)
ушул папкадагы эле эмес

2023-08-23 08:23 UTC, AziatAbd commented on src/store/lesson/lessonThunk.js
запросторду локально жасасаныз жакшы болот

2023-08-23 08:26 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/a1174424-1cce-41d9-a272-eb42a1d11ad1)
это тоже исправьте

2023-08-23 08:26 UTC, AziatAbd commented
добавьте snackbar'ы

2023-08-23 08:26 UTC, AziatAbd commented
добавьте snackbar'ы

2023-08-24 06:48 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/b0dbc6e9-a616-4934-a67c-aae82fec02f8)
удалить деген батпай калыптыр

2023-08-24 06:49 UTC, AziatAbd requested changes

2023-08-24 06:49 UTC, AziatAbd commented on src/config/axiosInstance.js
> +      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2OTI4NTY4NTgsImlhdCI6MTY5MjU5NzY1OCwidXNlcm5hbWUiOiJjb29sLm1lZ2EwMDdAZ21haWwuY29tIn0.sOraKgUX-NtFAp72pnWulNALnOsz1arl8GAUtlg8F2w'
статичный токен очуруп тыштан

2023-08-24 07:10 UTC, AziatAbd approved these changes

2023-08-24 07:10 UTC, merged