Feature/student layout
peaksoft-school/peaksoft-lms-js9 pull request #49
Opened 2023-09-07 22:11 UTC by AvazMAX

2023-09-08 13:24 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/a99c4211-961d-439e-9c8d-c0d1e845a1d1)
? даже если и опоздал, надо чтобы я смог отправлять дз

2023-09-08 14:19 UTC, AziatAbd requested changes

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/admin/courses/courses-page/Courses.jsx
> +      console.log(data)
консолки удаляем

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/student/home-page/LessonLayout.jsx
> +         />
её в одном месте нельзя вызвать, да?

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/student/home-page/LessonLayout.jsx
> +         />
один и тот же компонент вызывается везде, но используется в header'e

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/student/home-page/LessonLayout.jsx
> +   }, [])
каждому диспатчу отдельный useEffect

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/student/lessonsPage/task/TaskPage.jsx
> +                           />
здесь нужна textArea, а не input

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/student/lessonsPage/task/TaskPage.jsx
> +         </ContainerTask>
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/2520066d-b014-4913-9ba7-0ba40910651b)
сделайте типа так, чтобы был display flex

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/student/lessonsPage/task/TaskPage.jsx
> +                        />
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/fea96b22-6246-4412-a7f1-51dadf15713a)
сделайте так чтобы, если я нажал на Заголовок, то он как-то выделялся

2023-09-08 14:19 UTC, AziatAbd commented on src/pages/student/lessonsPage/test/TestInside.jsx
> +/* eslint-disable radix */
зачем это?

2023-09-08 14:19 UTC, AziatAbd commented on src/store/studentLayout/studentLayoutSlice.js
> +      })
зачем rejected если нету error состояния

2023-09-08 14:19 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/92e8cce0-d50d-4b1b-879d-b1094c3936d2)
правильные ответы не видны

2023-09-11 15:09 UTC, AvazMAX commented on src/pages/student/home-page/LessonLayout.jsx
> +         />
нет потому что header вызывается во многих местах

2023-09-11 15:15 UTC, AvazMAX commented on src/pages/student/lessonsPage/task/TaskPage.jsx
> +                           />
этот input для выбора файла TextArea используется ниже.

2023-09-11 15:19 UTC, AvazMAX commented
в тесте так и должно быть надо показать только те которые user выбрал.

2023-09-15 08:50 UTC, merged