added checkbox and radio
peaksoft-school/peaksoft-lms-js9 pull request #7
Opened 2023-07-09 06:47 UTC by AvazMAX

2023-07-09 07:50 UTC, Daniel-Narpaev approved these changes

2023-07-10 03:22 UTC, AziatAbd requested changes

2023-07-10 03:22 UTC, AziatAbd commented on src/components/UI/CheckBox.jsx
> +      </div>
откройте два отдельных компонента. Для checkbox и radio, а не одну

2023-07-10 03:22 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/peaksoft-lms-js9/assets/115453436/4087de0f-7d3f-4d3b-b327-7e04fee2c22a)
conflicts!

2023-07-10 03:23 UTC, nurzhigitabdymanapov approved these changes

2023-07-10 11:00 UTC, AziatAbd requested changes

2023-07-10 11:00 UTC, AziatAbd commented on src/components/UI/MyRadio.jsx
> +export const MyRadio = ({ value, labelOne, labelTwo }) => {
не добавляйте 'My' в компоненты 
также добавьте restProps на всякий случай

2023-07-10 11:00 UTC, AziatAbd commented on src/components/UI/MyRadio.jsx
> +      </div>
зачем всё это? Когда вызываю её выходит 2 radio button. Нужно просто вызвать Radio из Mui и дать нужные функции

2023-07-11 05:12 UTC, merged